# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mayor's Office for Innovation & Entrepreneurship
email: no-reply@usds.gov
description: >
  The Mayor's Office for Innovation & Entrepreneurship is expanding the startup pipeline, engaging the innovation ecosystem, and making City Hall open for business.
url: "https://innovatesac.org" # the base hostname & protocol for your site
twitter_username: innovatesac
github_username:  innovatesac
medium_url:
repository: innovatesac/innovatesac.org

# Build settings
markdown: kramdown

collections:
  # blog_summaries:
  program_summaries:
  # reports_to_congress:
  #   output: true

# defaults:
#   - scope:
#       path: ""
#       type: reports_to_congress
#     values:
#       layout: report-to-congress

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: innovatesac
logo: /img/mofie/favicon.png
